language: node_js
node_js:
  - '8'
  - '10'
  - 'node'
git:
  depth: 1
  quiet: true
env:
  - NODE_ENV=TEST CODECOV_TOKEN=f87dc2a0-28e5-49f4-911f-aa603dd6faa9
cache:
  yarn: true
  directories:
    - 'node_modules'
scripts:
  - yarn test
after_success:
  - codecov
